version: '3.8'

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_ID=TinyLlama/TinyLlama-1.1B-Chat-v1.0
    command: ["--model-id", "TinyLlama/TinyLlama-1.1B-Chat-v1.0"]
    volumes:
      - ./models:/data
    ports:
      - "8082:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - tgi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  model-manager:
    build: ./model-manager
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - TGI_HOST=http://tgi:8000  # This stays the same as it's internal
    volumes:
      - ./models:/models
    ports:
      - "8081:8081"
    networks:
      - tgi-network
    depends_on:
      tgi:
        condition: service_healthy
    restart: unless-stopped

  openwebui:
    build: ./openwebui
    environment:
      - OPENAI_API_BASE=http://tgi:8000/v1  # This stays the same as it's internal
      - OPENAI_API_KEY=not-needed
    ports:
      - "8080:8080"
    depends_on:
      - tgi
    restart: unless-stopped
    networks:
      - tgi-network

networks:
  tgi-network:
    driver: bridge

volumes:
  models: