version: '3.8'

services:
  vllm:
    build: ./vllm
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GPU_COUNT=2
    volumes:
      - ./models:/models
    ports:
      - "8000:8000"
    command: ["python3", "-m", "vllm.entrypoints.openai.api_server", "--host", "0.0.0.0", "--port", "8000"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openwebui:
    build: ./openwebui
    environment:
      - OPENAI_API_BASE=http://vllm:8000/v1
      - OPENAI_API_KEY=not-needed
    ports:
      - "8080:8080"
    depends_on:
      - vllm

  model-manager:
    build: ./model-manager
    volumes:
      - ./models:/models
    ports:
      - "8081:8081"

volumes:
  models: