version: '3.8'

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_ID=mistralai/Mistral-7B-Instruct-v0.3
      - HF_TOKEN=${HF_TOKEN}
    command: [
      "--model-id", "mistralai/Mistral-7B-Instruct-v0.3",
      "--max-input-length", "2048",
      "--max-total-tokens", "4096",
      "--hostname", "0.0.0.0"
    ]
    volumes:
      - ./models:/data/models
    ports:
      - "8081:80"
    networks:
      - ai-network

  model-manager:
    build: ./model-manager
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - TGI_HOST=http://tgi:80
      - MODEL_PATH=/models
    volumes:
      - ./models:/models
    ports:
      - "8082:8082"
    networks:
      - ai-network
    depends_on:
      - tgi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE=http://tgi:80/v1
      - OPENAI_API_KEY=not-needed
      - ENDPOINTS=http://tgi:80/v1
      - DEFAULT_ENDPOINT=http://tgi:80/v1
      - SERVER_HOST=0.0.0.0
    ports:
      - "8080:8080"
    networks:
      - ai-network
    depends_on:
      - tgi

networks:
  ai-network:
    driver: bridge