version: '3.8'

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${HF_TOKEN}
    command: [
      "--sharded", "true",
      "--num-shard", "2",
      "--max-batch-prefill-tokens", "2048",
      "--max-batch-total-tokens", "12288",
      "--max-concurrent-requests", "64",
      "--cuda-memory-fraction", "0.95",
      "--hostname", "0.0.0.0"
    ]
    volumes:
      - ./models:/data/models
    ports:
      - "8081:80"
    networks:
      - ai-network

  model-manager:
    build: ./model-manager
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - TGI_HOST=http://tgi:80
      - MODEL_PATH=/models
      - DEFAULT_MODEL=mistralai/Mistral-7B-Instruct-v0.3
    volumes:
      - ./models:/models
    ports:
      - "8082:8082"
    networks:
      - ai-network
    depends_on:
      - tgi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE=http://tgi:80/v1
      - OPENAI_API_KEY=not-needed
      - ENDPOINTS=http://tgi:80/v1
      - DEFAULT_ENDPOINT=http://tgi:80/v1
      - SERVER_HOST=0.0.0.0
    ports:
      - "8080:8080"
    networks:
      - ai-network
    depends_on:
      - tgi

networks:
  ai-network:
    driver: bridge