version: '3.8'

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${HF_TOKEN}
    command: [
      "--sharded", "true",
      "--num-shard", "2",
      "--max-batch-prefill-tokens", "2048",
      "--max-batch-total-tokens", "12288",
      "--max-concurrent-requests", "64",
      "--cuda-memory-fraction", "0.95",
      "--hostname", "0.0.0.0",
      "--port", "80"
    ]
    volumes:
      - ./models:/data/models
    ports:
      - "8081:80"
    networks:
      - ai-network

  model-manager:
    build: ./model-manager
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - TGI_HOST=http://tgi:80  # Internal network address
      - MODEL_PATH=/models
      - PORT=8082  # Explicitly set port
    volumes:
      - ./models:/models
    ports:
      - "8082:8082"  # Fixed port mapping
    networks:
      - ai-network
    depends_on:
      - tgi

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE=http://tgi:80/v1  # Internal network address
      - OPENAI_API_KEY=not-needed
      - SERVER_HOST=0.0.0.0
      - ENDPOINTS=http://localhost:8081/v1  # External address for UI
    ports:
      - "8080:8080"
    networks:
      - ai-network
    depends_on:
      - tgi

networks:
  ai-network:
    driver: bridge