version: '3.8'

services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_ID=mistralai/Mistral-7B-Instruct-v0.2-fr
      - CORS_ALLOW_ORIGINS=*
    command: [
      "--model-id", "mistralai/Mistral-7B-Instruct-v0.2-fr",
      "--max-input-length", "2048",
      "--max-total-tokens", "4096",
      "--cors-allow-origins", "*"
    ]
    ports:
      - "8081:80"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE=http://localhost:8081/v1
      - OPENAI_API_KEY=not-needed
      - ENDPOINTS=http://localhost:8081/v1
      - DEFAULT_ENDPOINT=http://localhost:8081/v1
      - SERVER_HOST=0.0.0.0
    ports:
      - "8080:8080"  # OpenWebUI interface
    depends_on:
      - tgi
    restart: unless-stopped
    networks:
      - tgi-network

networks:
  tgi-network:
    driver: bridge

volumes:
  models: